### ISSUE TITLE
How to download VIST dataset?

### ISSUE THREAD

**Issue by Thinking-more** [passerby233/Collection-of-Visual-Storytelling-StoryNLP#1]
Hello, I would like to know how to get access to download the VIST dataset. I sent an email to the contact person at the official VIST website, but no one has replied even after a week. It seems that this dataset is no longer open?

**Comment by passerby233** [comment]
> Hello, I would like to know how to get access to download the VIST dataset. I sent an email to the contact person at the official VIST website, but no one has replied even after a week. It seems that this dataset is no longer open?

http://visionandlanguage.net/VIST/dataset.html
So, what's the specific problem? It seems the corresponding data on google drive works well. Note that google drive does not supply services for some areas and you need some tool (you know).

@RENJZ1026

**Comment by Thinking-more** [comment]
Thank you for your help, I have solved the problem.

**Comment by youthHan** [comment]
Hi, I'm working on VIST task and the Google Drive of the VIST dataset prompts to ask for permission from the owners. I have changed my IP to the States, however, the same issue exists. It would be much appreciated if you can share a copy for my pure research purpose. @passerby233

**Comment by passerby233** [comment]
@youthHan 
It may take some time for the owner to check your application. 
I'm not a member of the dataset team nor am I responsible for maintaining it.
